### ISSUE TITLE
Todo Board

### ISSUE THREAD

**Issue by UltimateGG** [UltimateGG/zentrix#6]
- [x] Delete message
- [x] Swipeable menu/nav
- [x] Markdown
- [x] Edit messages
- [ ] Upload media (camera roll for mobile, file picker for web)
- [ ] Todo lists
- [ ] Encrypted chats
- [ ] Reordering of chats

**Comment by UltimateGG** [comment]
I added a file picker works on ios and web for pfp, but the api is trash because later on ill need videos, also this loads them as a string (Maybe no way around that though)
So probably will use diff api. Not going to implement reset of file pickers rn till more optimized solution

**Comment by UltimateGG** [comment]
Also eventually need to strip exif out of all media files

**Comment by thangtq-pionero** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
joseabraham, @PeakyCryptos, @nfwsncked, @marcinja, @idkDemo, @higherdawn, @0xethsign, @faheelsattar, @cybernetics, @xenowits, @tinhb92, @vbrvk, @e1block, @AdamTVL, @dibakarsutradhar, @damoncro, @sistemd, @jqphu, @tianbaoluo, @Jite01
